import Head from 'next/head';
import { Container } from '@mui/material';
import { ReactElement } from 'react';
import BaseLayout from '@/layouts/BaseLayout';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container maxWidth="lg"></Container>
        </>
    );
}

Home.getLayout = function getLayout(page: ReactElement) {
    return <BaseLayout>{page}</BaseLayout>;
};
